// Code generated by "stringer -linecomment -type GoUcError -output ./unicorn_go_const_stringers.go ./unicorn_go_const.go"; DO NOT EDIT.

package unicorn

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UCGO_ERR_REG_BATCH_MALLOC - -1]
}

const _GoUcError_name = "Error in uc_reg_..._batch_helper's malloc()"

var _GoUcError_index = [...]uint8{0, 43}

func (i GoUcError) String() string {
	idx := int(i) - -1
	if i < -1 || idx >= len(_GoUcError_index)-1 {
		return "GoUcError(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GoUcError_name[_GoUcError_index[idx]:_GoUcError_index[idx+1]]
}
